# standard jekyll configuration

title: Open Government Platform
url: http://ogpl.github.io/
repo_name: ogpl.github.io
branch: master

#global settings, no need to change these
root_url: http://ogpl.github.io
org_name: ogpl

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ['README.md']

# prose settings
prose:
  siteurl: http://ogpl.github.io
  media: "images"
  metadata:
    _posts:
      - name: "categories"
        field:
          element: "hidden"
          value:
            - "post"
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "default"
      - name: "item"
        field:
          element: "select"
          label: "Item"
          placeholder: "Select an Item"
          options:
            - name: "Item 1"
              value: "item1"
            - name: "Item 2"
              value: "item2"
          selected: "item2"

